events = [
    {
        'id': 1,
        'name': 'Interest Meeting',
        'description': 'Join us for our upcoming interest meetings! The Computer Science Club is excited to announce that we will be hosting multiple meetings each week, each with a different focus. We want to find the best times for our potential members, so we\'re offering several options. Come and learn more about what our club has to offer and how you can get involved. We hope to see you there!',
        'startDate': '2025-09-09 19:00',
        'endDate': '2025-09-09 20:00',
        'location': 'E281',
    },
    {
        'id': 2,
        'name': 'Git/GitHub Workshop',
        'description': 'Join us for our workshop on the basics of using Git and GitHub! In this workshop, we will cover the fundamentals of version control using Git, as well as how to use GitHub for collaboration and project management. Whether you\'re new to Git or looking to brush up on your skills, this workshop is perfect for you. We will provide hands-on exercises and plenty of opportunities for questions and discussion. Don\'t miss out on this chance to learn more about one of the most important tools in modern software development!',
        'startDate': '2025-09-16 19:00',
        'endDate': '2025-09-16 20:00',
        'location': 'E281',
    },
    {
        'id': 3,
        'name': 'Professional Development Workshop',
        'description': 'Join us for our upcoming Professional Development Workshop! The Computer Science Club is excited to announce that we will be hosting a workshop focused on helping students develop the skills they need to succeed in their careers. We will cover topics such as resume writing, interview preparation, and networking strategies. Don\'t miss this opportunity to gain valuable insights and make connections with industry professionals!',
        'startDate': '2025-09-23 19:00',
        'endDate': '2025-09-23 20:00',
        'location': 'E281',
    },
    {
        'id': 4,
        'name': 'Basic Web Development Workshop',
        'description': 'Join us for our upcoming Basic Web Development Workshop! The Computer Science Club is excited to announce that we will be hosting a workshop focused on the fundamentals of web development. Whether you\'re a complete beginner or looking to refresh your skills, this workshop is for you. We will cover topics such as HTML, CSS, and JavaScript, and provide hands-on exercises to help you build your own web pages. Don\'t miss this opportunity to learn more about web development and how you can get started!',
        'startDate': '2025-09-30 19:00',
        'endDate': '2025-09-30 20:00',
        'location': 'E281',
    },
    {
        'id': 5,
        'name': 'Trivia Night',
        'description': 'Join us for our upcoming Trivia Night! The Computer Science Club is excited to announce that we will be hosting a fun and engaging trivia night, where you can test your knowledge on a variety of topics. Gather your friends and form a team, or come solo and meet new people! Prizes will be awarded to the top teams, so don\'t miss out on this chance to show off your trivia skills and have a great time!',
        'startDate': '2025-10-07 19:00',
        'endDate': '2025-10-07 20:00',
        'location': 'E281',
    },
    {
        'id': 6,
        'name': 'Advising/Class Schedule Workshop',
        'description': 'Join us for our upcoming Advising/Class Schedule Workshop! The Computer Science Club is excited to announce that we will be hosting a workshop focused on helping students navigate their course schedules and academic advising. Whether you\'re a new student or looking to make changes to your current schedule, this workshop is for you. We will provide guidance on course selection, degree requirements, and tips for academic success. Don\'t miss this opportunity to get the support you need for a successful semester!',
        'startDate': '2025-10-14 19:00',
        'endDate': '2025-10-14 20:00',
        'location': 'E281',
    },
    {
        'id': 7,
        'name': 'Arduino Workshop',
        'description': 'Join us for our upcoming Arduino Workshop! The Computer Science Club is excited to announce that we will be hosting a workshop focused on introducing students to the world of Arduino and physical computing. Whether you\'re a complete beginner or have some experience, this workshop is for you. We will cover the basics of Arduino programming, hardware components, and provide hands-on exercises to help you create your own projects. Don\'t miss this opportunity to learn more about Arduino and how you can get started!',
        'startDate': '2025-10-21 19:00',
        'endDate': '2025-10-21 20:00',
        'location': 'E281',
    },
    {
        'id': 8,
        'name': 'Generative AI Workshop',
        'description': 'Join us for our upcoming Generative AI Workshop! The Computer Science Club is excited to announce that we will be hosting a workshop focused on exploring the world of generative AI and its applications. Whether you\'re a complete beginner or have some experience, this workshop is for you. We will cover the basics of generative models, including GANs and VAEs, and provide hands-on exercises to help you create your own AI-generated content. Don\'t miss this opportunity to learn more about generative AI and how you can get started!',
        'startDate': '2025-10-28 19:00',
        'endDate': '2025-10-28 20:00',
        'location': 'E281',
    },
    {
        'id': 9,
        'name': 'TBD',
        'description': 'This event is to be determined. Stay tuned for more information about this exciting upcoming event hosted by the Computer Science Club!',
        'startDate': '2025-11-04 19:00',
        'endDate': '2025-11-04 20:00',
        'location': 'E281',
    },
    {
        'id': 10,
        'name': 'TBD',
        'description': 'This event is to be determined. Stay tuned for more information about this exciting upcoming event hosted by the Computer Science Club!',
        'startDate': '2025-11-11 19:00',
        'endDate': '2025-11-11 20:00',
        'location': 'E281',
    },
    {
        'id': 11,
        'name': 'C#/.NET Workshop',
        'description': 'Join us for our upcoming C#/.NET Workshop! The Computer Science Club is excited to announce that we will be hosting a workshop focused on introducing students to the world of C# and .NET development. Whether you\'re a complete beginner or have some experience, this workshop is for you. We will cover the basics of C# programming, .NET framework, and provide hands-on exercises to help you create your own projects. Don\'t miss this opportunity to learn more about C# and .NET and how you can get started!',
        'startDate': '2025-11-18 19:00',
        'endDate': '2025-11-18 20:00',
        'location': 'E281',
    },
    {
        'id': 12,
        'name': 'Krunker Game Night',
        'description': 'Join us for our upcoming Krunker Game Night! The Computer Science Club is excited to announce that we will be hosting a fun-filled evening of gaming, where you can compete with your fellow club members in the popular online game Krunker. Whether you\'re a seasoned player or new to the game, this event is for you. Bring your friends, form teams, and get ready for some friendly competition. Don\'t miss out on the chance to showcase your skills and have a great time!',
        'startDate': '2025-12-02 19:00',
        'endDate': '2025-12-02 20:00',
        'location': 'E281',
    },
]
